### ISSUE TITLE
四書章句集注學而第一混入爲政第二

### ISSUE THREAD

**Issue by lytccc** [Ancient-China-Books/ancient-china-books.github.io#4]
四書章句集注
[學而第一](https://ancient-china-books.github.io/sishuzhangjujizhu/OEBPS/Text/part07.htm#sigil_toc_id_1)
混入爲政第二

**Comment by douglarek** [comment]
嗯，感谢反馈，这个不是混入，本身就是一个 网页，目录按锚点分成的两章。
